! chpot.f90:   A Polarisation consistent charge-fitting tool 
!              A Molecolab Tool www.dcci.unipi.it/molecolab/tools
!
! Copyright (C) 2014, 2015 
!   S. Caprasecca, C. Curutchet, S. Jurinovich, B. Mennucci
!
! This program is free software: you can redistribute it and/or modify
!   it under the terms of the GNU General Public License as published by
!   the Free Software Foundation, either version 3 of the License, or
!   (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
!   but WITHOUT ANY WARRANTY; without even the implied warranty of
!   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!   GNU General Public License for more details.
!
! A copy of the GNU General Public License can be found in LICENSE or at
!   <http://www.gnu.org/licenses/>.
!
!
! -------------------------------------------------------------------
!     Subroutine to compute the potential generated by a set of
!     charges over the gridpoints.
!
Subroutine chpot(nch,ngr,Chg,R,Vch)
IMPLICIT REAL*8 (A-H,O-Z)
DIMENSION Chg(nch),R(4,ngr,nch),Vch(ngr)
DO I=1,ngr
  Vch(I) = 0.0d0
  DO J=1,nch
    Vch(I) = Vch(I) + Chg(J)/R(4,I,J)
  ENDDO
ENDDO
RETURN
End Subroutine
