real*8 function error(lpol)

  use constants
  use mmpoldata
  use gespinfo
  use espinfo

  implicit real*8 (a-h,o-z)

  logical :: lpol
  real*8  :: V(NGrd)

 2000 format(' PESP: Computing fit error.')
 2010 format(' ESP:  Computing fit error.')

! Compute potential generated by charge or charge+dipole distribution

  if (lpol) then
    if (iprt.ge.2) write(iout,2000)
    call potchgdip(NGrd,NChg,Rij,Rij3,RChGr,D,scrcp,qpesp,V,ddpesp)
  else
    if (iprt.ge.2) write(iout,2010)
    call potchg(NGrd,NChg,qesp,RChGr(4,:,:),V)
  endif

! Compute fit error

  error = rms(NChg,VQM,V)

  return

end function
