! error.f90:       A Polarisation consistent charge-fitting tool 
!                  A Molecolab Tool www.molecolab.dcci.unipi.it/tools
!
! Copyright (C) 2014, 2015, 2016, 2017
!   S. Caprasecca, C. Curutchet, S. Jurinovich, B. Mennucci
!
! This program is free software: you can redistribute it and/or modify
!   it under the terms of the GNU General Public License as published by
!   the Free Software Foundation, either version 3 of the License, or
!   (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
!   but WITHOUT ANY WARRANTY; without even the implied warranty of
!   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!   GNU General Public License for more details.
!
! A copy of the GNU General Public License can be found in LICENSE or at
!   <http://www.gnu.org/licenses/>.
!
real*8 function error(lpol,charges)

  use constants
  use mmpoldata
  use gespinfo
  use espinfo

  implicit real*8 (a-h,o-z)

  logical :: lpol
  real*8  :: V(NGrd), charges(NChg)

 2000 format(' PESP: Computing fit error.')
 2010 format(' ESP:  Computing fit error.')

! Compute potential generated by charge or charge+dipole distribution

  if (lpol) then
    if (iprt.ge.2) write(iout,2000)
    call potchgdip(NGrd,NChg,Rij,Rij3,RChGr,D,scrcp,charges,V,ddpesp)
  else
    if (iprt.ge.2) write(iout,2010)
    call potchg(NGrd,NChg,charges,RChGr(4,:,:),V)
  endif

! Compute fit error

  error = rms(NChg,VQM,V)

  return

end function
